version: '3.8'

services:
  kredinbizden_loan:
    image: mysql:latest
    container_name: kredinbizden_loan
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: kredinbizden_loan
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
