version: '3.8'

services:
  kredinbizden_offer:
    image: mysql:latest
    container_name: kredinbizden_offer
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: kredinbizden_offer
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
