version: '3.8'

services:
  kredinbizden_credit_card:
    image: mysql:latest
    container_name: kredinbizden_credit_card
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: kredinbizden_credit_card
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
