version: '3.8'

services:
  kredinbizde_user_db:
    image: postgres:latest
    container_name: kredinbizde_user_db
    environment:
      POSTGRES_DB: kredinbizde_user_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
